### PR TITLE
Mech/vehicle/omnivehicle turret fixes & improvements

### PR DESCRIPTION
**Pull request by lbmaian**
Mech turrets:
* Fix quad mechs to allow both torso and head turrets (they're considered different types of mech turrets).
* Revamp mech turret code to fix edge cases and allow equipment.
* Align mech turret/rear-mounting code, both in lib and GUI logic.
* Drag&drop weapon/equipment retains mech turreted status.
* Displaced weapon/equipment (when dragging another equipment onto it, requiring reallocation) also retains mech turreted status.
* Disallow mounting ammo in mech turret. (Technically, I think ammo can be allocated to the turret but shouldn't count for turret tonnage, which functionally should be the same as disallowing turreted ammo.)

Vehicle turrets:
* Add rear turret tonnage to info bar. To help make it fit in the info bar, turret tonnages are hidden if corresponding turret doesn't exist, and reduce width of some boxes there.
* Fix error if removing CV turret and adding item without selecting location.
* Fix regression from b46d085 that inadvertently unset rear turret armor.
* Fix changing from dual turrets to single turret not removing rear turret location.
* Fix regression from 2415ab5 and related omnivehicle code that broke turrets on non-omnivehicles on wide CV GUI. Specifically, omnivehicle code didn't properly unset turret max tonnage when disabled, and the wide CV GUI specifically resets them to 0 even for non-omnivehicles.

Omnivehicle turrets:
* Add turret tonnage limits to info bar, color-coded in same way as total tonnage. 
* Turret tonnage from items now checked against max turret tonnage as part of pre-save/export validation. Also improve this validation error behavior a bit.
* Avoid unsetting turret tonnage for locked chassis (omni variants).
* Fix some weird edge cases by ensuring turret tonnage is kept in sync b/w UI and model.
* Fix omnivehicle rear turret tonnage limit not being saved/loaded.
* Unlocking omni chassis no longer unchecks omni checkbox and zeros out turret tonnages.

Misc omni stuff:
* Fix wide CV UI not resetting omni variant combobox when loading new vehicle.
* Fix lock chassis button getting out of sync with omni checkbox (applies for both omnimechs and omnivees).
* Fix right sponson turret not being propagated to omni variants.
* Remove omnivehicle max tonnage code from sponson turrets since they're unrelated to omnivehicles, and some other internal changes.

### CODE REVIEW

**Comment by WEKarnesky** [comment]
Thank you for your submission.
My apologies for the delay, I will be reviewing it later tonight or tomorrow.

**Comment by lbmaian** [comment]
Gonna include a couple more turret-related fixes, hold on a bit.

**Comment by lbmaian** [comment]
Bundled omnivehicle turret fixes. Ok should be good to go.

**Review by WEKarnesky — APPROVED** [review]

**Comment by lbmaian** [comment]
Thanks for merging. I'll have another PR upcoming with more fixes (unrelated to turrets!) in a day or so.

**Pull request merged**
