### PR TITLE
Develop

### LINKED ISSUE #111: Bug: Quirks not loaded or saved
As noted by WEKarnesky is issue #90, loading and saving of quirks is not saved in anything.

### PR DESCRIPTION
**Pull request by olaughlj**
Fixed #111 - Updated SSW to save/load quirks when saving/loading mech files

### CODE REVIEW

**Comment by WEKarnesky** [comment]
I have only had time to skim the changes, on a brief look, they seem solid.  tomorrow after work I will do a deeper read and basic regression test before approving.  Thank you for this contribution!

**Comment by olaughlj** [comment]
I am also going to make some quality of life improvements to the quirk dialog (double clicking to move items from one list to another) and move the done button to the bottom right of the dialog instead of the top middle but that probably won't be for a couple of days.

**Comment by WEKarnesky** [comment]
Sounds great.  I forget the status of vehicle quirks at the moment, but if they are similar to where mech quirks are, then you might do it for there as well.

**Comment by olaughlj** [comment]
Yep was planning on looking at SAW as well.

**Comment by olaughlj** [comment]
Updates the SSW Quirks Dialog are now included in this pull request.

**Pull request merged**
