### PR TITLE
Merge pull request #66 from Solaris-Skunk-Werks/master

### PR DESCRIPTION
**Pull request by VincentDegrassa**
update develop branch

Equipment Files with some of the latest Era changes
[Equipment.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3705053/Equipment.zip)

### CODE REVIEW

**Comment by VincentDegrassa** [comment]
Chassis and Engine changes
[Engine&Chassis.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3705058/Engine.Chassis.zip)

**Comment by VincentDegrassa** [comment]
Component changes
[Components.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3705070/Components.zip)

**Comment by VincentDegrassa** [comment]
I think I might have chang
[More.components.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3705072/More.components.zip)
ed these files also

**Comment by WEKarnesky** [comment]
I have moved these to an issue ticket, #72

**Pull request closed without merging**
